# Site settings
title: "Tony Rossi's Cybersecurity Portfolio"
description: >
  A portfolio showcasing my expertise in vulnerability management, threat modeling,
  GRC, and entrepreneurship.
baseurl: ""                    # Leave empty if deploying at the root domain
url: "https://xtonyknucklesx.github.io"  # Your GitHub Pages URL
github_username: xtonyknucklesx
minimal_mistakes_skin: "dark"
search: true
lunr:
  search_within_pages: true
locale: en-US
logo: /assets/img/logo3.png

# Author details
author:
  name: "Tony Rossi"
  email: "anthony.rossi1983@gmail.com"

# Build settings
markdown: kramdown

# Theme configuration using a remote theme
remote_theme: mmistakes/minimal-mistakes@4.26.2  # Use the appropriate version or remove the version tag if not needed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Optional: Site defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      read_time: true
      layout: single
      author: "Tony Rossi"

# Minimal Mistakes theme settings (optional)
header:
  title: "Tony Rossi's Cybersecurity Portfolio"
  nav:
    - title: "About"
      url: "/#about"
    - title: "Work"
      url: "/#work"
    - title: "Projects"
      url: "/#projects"
    - title: "Blog"
      url: "/blog"
    - title: "Contact"
      url: "/#contact"

footer:
  text: "© 2025 Tony Rossi. All rights reserved."

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor